modified:   README 	modified:   cliff/desktop 	modified:   cliff/feliz 	modified:   cliff/listgen 	modified:   cliff/partitioning 	modified:   cliff/various 	deleted:    common/feliz-uefi 	new file:   common/feliz.english 	modified:   common/shared 	modified:   squiff/desktop 	modified:   squiff/feliz 	modified:   squiff/listgen 	modified:   squiff/partitioning 	modified:   squiff/various Incorporate English translation file

diff --git a/squiff/desktop b/squiff/desktop
--- a/squiff/desktop
+++ b/squiff/desktop
@@ -15,7 +15,7 @@
 # UserName      75     ChangeRootPartition 356
 # Hostname      85     ChangeSwapPartition 364
 # PickLuxuries  93     ChangePartitions    372
-# ShoppingList 120     AddExtras           383    
+# ShoppingList 120     AddExtras           383
 
 getkeymap() {
   ListKbs=`cat keymaps.list`
@@ -23,8 +23,8 @@ getkeymap() {
   for k in ${ListKbs[@]}; do
     keyboards="$keyboards $k"
   done
-  local Message="Scroll through this list, or type a letter, to find your keyboard."
-  listgen1 "${keyboards}" "Keyboards" "nocancel"
+  local Message="${_getkeymap_Message}."
+  listgen1 "${keyboards}" "${_Keyboards}" "nocancel"
   Countrykbd=$(cat output.file)
   loadkeys ${Countrykbd} 2>> feliz.log
 }
@@ -37,8 +37,8 @@ setlocale() {
     Counter=$((Counter+1))
     Options[${Counter}]="UTF-8"
   done
-  local Message="Scroll through this list, or type a letter, to find your locale. This will be used to find the best mirrors for downloading your system"
-  dialog --backtitle "$Backtitle" --title " Locales " --nocancel \
+  local Message="${_setlocale_Message}"
+  dialog --backtitle "$Backtitle" --title " - ${_Locales} - " --nocancel \
       --menu "\n$Message\n" 18 55 $Counter "${Options[@]}" 2> output.file
   CountryLocale="$(cat output.file).UTF-8"
   CountryCode=(`cat output.file | cut -c4-5`)
@@ -50,70 +50,92 @@ SetTimeZone() {
   for z in ${Zones[@]}; do
     passzones="$passzones $z"
   done
-  local Message="To set the system clock, please choose the World Zone of your location."
-  listgen1 "${passzones}" "World zones" "nocancel"
+  local Message="${_SetTimeZone_Message1} ${_SetTimeZone_Message2}."
+  listgen1 "${passzones}" "${_World_Zones}" "nocancel"
   ZONE=$(cat output.file)
   SubZones=(`timedatectl list-timezones | grep ${ZONE} | sed 's/^.*\///'`)
   passzones=""
   for z in ${SubZones[@]}; do
     passzones="$passzones $z"
   done
-  local Message="Now select your nearest city from this list."
-  listgen1 "$passzones" "Cities in ${ZONE}" "nocancel"
+  local Message="${_Set_City_Message}."
+  listgen1 "$passzones" "${_Cities} ${ZONE}" "nocancel"
   SUBZONE=$(cat output.file)
 }
 
 UserName() {
-	local Message="Enter a name for the primary user of the new system.\nIf you don't create a username here, a default user called 'archie' will be set up"
-  dialog --backtitle "$Backtitle" --title " User name " --nocancel\
+  local Message="${_UserName_Message1}\n ${_UserName_Message2}\n ${_UserName_Message3}"
+  dialog --backtitle "$Backtitle" --title " - ${_User_Name} - " --nocancel\
       --inputbox "\n$Message\n" 18 50 2> output.file
   Response=$(cat output.file)
   Entered=${Response,,}
-	case $Entered in
-		"") UserName="archie"
-		;;
-		*) UserName=${Entered}
-	esac
+  case $Entered in
+    "") UserName="archie"
+    ;;
+    *) UserName=${Entered}
+  esac
 }
 
 SetHostname() {
-	Entered="arch-linux"
-	local Message="A hostname is needed. This will be a unique name to identify your device on a network.\nIf you do not enter one, the default hostname of 'arch-linux' will be used."
-  dialog --backtitle "$Backtitle" --title " Hostname " --nocancel\
+  Entered="arch-linux"
+  local Message="${_SetHostName_Message1}\n ${_SetHostName_Message2}\n ${_SetHostName_Message3}"
+  dialog --backtitle "$Backtitle" --title " - ${_Hostname} - " --nocancel\
       --inputbox "\n$Message\n" 16 40 2> output.file
   Response=$(cat output.file)
   Entered=${Response,,}
-	case $Entered in
-		"") HostName="arch-linux"
-		;;
-		*) HostName=${Entered}
-	esac
+  case $Entered in
+    "") HostName="arch-linux"
+    ;;
+    *) HostName=${Entered}
+  esac
 }
 
 PickLuxuries() { # User selects any combination from a store of extras
-Category="Continue"
-case "${LuxuriesList}" in
-  "") local Message="Now you have the option to add extras, such as a web browser, etc. If you want only a base Arch installation, exit without choosing any extras."
+  case "${LuxuriesList}" in
+  "") local Message="${_PickLuxuries_Message1}\n ${_PickLuxuries_Message2}"
   ;;
-  *) local Message="You can add more items, or select items to delete."
+  *) local Message="${_PickLuxuries_Message5}"
   esac
-until [ $Category = "Done" ]
+  Category="Continue"
+until [ $Category = "${_Done}" ]
 do
-  # First select a category
-  listgen1 "$Categories" " Categories " "Done"
-  if [ $? -gt 0 ]; then # <Cancel> selected
+ # First select a category
+  HowMany=`echo ${_Categories_List} | wc -w` # Count words
+  echo ${_Categories_List} | sed "s/ /\\n/g" > feliz.output # Copy categories to file
+  Counter=1
+  ItemCounter=1
+  Width=50
+  Options=()
+  until [ $ItemCounter -gt $HowMany ] # Prepare numbered list from file
+  do
+    Options[$((Counter))]=${ItemCounter}
+    Counter=$((Counter+1))
+    Options[${Counter}]=`sed -n "$ItemCounter p" feliz.output`
+    Counter=$((Counter+1))
+    ItemCounter=$((ItemCounter+1))
+  done
+
+  # Use $ItemCounter and ${Options[@]} array in menu dialog
+  dialog --backtitle "$_Backtitle" --title " - ${_Categories} - " --no-shadow --ok-button "${_Select}" --menu "$Message\n" 18 50 $ItemCounter "${Options[@]}" 2> feliz.output # Output is line number of selection
+  RetVal=$?
+  if [ $RetVal -gt 0 ]; then # <Cancel> selected
     break
   else
-    Category=$(cat output.file)
+    Selected=`cat feliz.output`
+    # Use selected number to get category for script use
+    Category=${Categories[${Selected}]} # English
+    # Get selection description in user language from $Options array
+    Selected=$((Selected*2))
+    _Category=${Options[${Selected}]} # User language
   fi
-  # Then shop in that category  
+  # Then shop in that category
   ShoppingList
-  local Message="Added so far: ${LuxuriesList}\nYou can now choose from any of the other lists, or choose <Done> to finish this part of the setup"
+  local Message="${_PickLuxuries_Message3}: ${LuxuriesList}\n ${_PickLuxuries_Message4} ${_PickLuxuries_Message6}"
 done
 if [ -n "${LuxuriesList}" ]; then
   Scope="Full"
 else
-  Scope="Basic"  
+  Scope="Basic"
 fi
 }
 
@@ -121,34 +143,35 @@ ShoppingList() {
   # Called by PickLuxuries after a category has been chosen.
   local Complete=0
   case "$LuxuriesList" in
-  "") local Title="Choose your first category"
-  ;;
-  *) local Title="Choose your next category"
-  esac
+    "") local Title="${_ShoppingList_Title1}"
+    ;;
+    *) local Title="${_ShoppingList_Title2}"
+    esac
   while [ $Complete -eq 0 ]
   do
-    local Message="Added so far: ${LuxuriesList}"
+    local Message="${_Addedsofar}: ${LuxuriesList}"
     # Pass category to listgen2 for user to choose one item;
     case $Category in
-      "Accessories") listgen2 "$Accessories" "Accessories" "Done" "LongAccs"
+      "Accessories") listgen2 "$Accessories" "${_Category}" "${_Done}" "LongAccs"
       ;;
-      "Desktop_Environments") listgen2 "$Desktops" "Desktops" "Done" "LongDesk"
+      "Desktop_Environments") listgen2 "$Desktops" "${_Category}" "${_Done}" "LongDesk"
       ;;
-      "Graphical") listgen2 "$Graphical" "Graphical" "Done" "LongGraph"
+      "Graphical") listgen2 "$Graphical" "${_Category}" "${_Done}" "LongGraph"
       ;;
-      "Internet") listgen2 "$Internet" "Internet" "Done" "LongNet"
+      "Internet") listgen2 "$Internet" "${_Category}" "${_Done}" "LongNet"
       ;;
-      "Multimedia") listgen2 "$Multimedia" "Multimedia" "Done" "LongMulti"
+      "Multimedia") listgen2 "$Multimedia" "${_Category}" "${_Done}" "LongMulti"
       ;;
-      "Office") listgen2 "$Office" "Office" "Done" "LongOffice"
+      "Office") listgen2 "$Office" "${_Category}" "${_Done}" "LongOffice"
       ;;
-      "Programming") listgen2 "$Programming" "Programming" "Done" "LongProg"
+      "Programming") listgen2 "$Programming" "${_Category}" "${_Done}" "LongProg"
       ;;
-      "Window_Managers") listgen2 "$WindowManagers" "Window_Managers" "Done" "LongWMs"
+      "Window_Managers") listgen2 "$WindowManagers" "${_Category}" "${_Done}" "LongWMs"
       ;;
       *) break
     esac
-    if [ $? -gt 0 ]; then # <Cancel> selected
+    RetVal=$?
+    if [ $RetVal -gt 0 ]; then # <Cancel> selected
       break
     else
       Picked=$(cat output.file)
@@ -158,31 +181,29 @@ ShoppingList() {
     do
       if [ ${lux} = ${Picked} ]; then
         Temp=""
-        dialog --yes-label "Keep" --no-label "Delete" \
-      --backtitle "$Backtitle" --title " Information " --no-shadow \
-    --yesno "\n  '$Picked' is already in your shopping list. Do you wish to delete it or keep it?" 10 60
+        dialog --yes-label "${_Keep}" --no-label "${_Delete}" --backtitle "$Backtitle" --title " - ${_Information} - " --no-shadow --yesno "\n  '$Picked' ${_Already1}\n ${_Already2}" 10 60
         case $? in
-        0) continue 2 # Keep $LuxuriesList as it is and return to top of enclosing loop
-         ;;
-        *) for lux in $LuxuriesList
-          do
-            if [ ${lux} != ${Picked} ]; then
-              Temp="$Temp $lux"
-            fi
-          done
-          LuxuriesList="$Temp"
-          continue 2 # Revise $LuxuriesList and return to top of enclosing loop
+          0) continue 2 # Keep $LuxuriesList as it is and return to top of enclosing loop
+          ;;
+          *) for lux in $LuxuriesList
+            do
+              if [ ${lux} != ${Picked} ]; then
+                Temp="$Temp $lux"
+              fi
+            done
+            LuxuriesList="$Temp"
+            continue 2 # Revise $LuxuriesList and return to top of enclosing loop
         esac
       fi
     done
-    # Then carry out any specific tests and add the item to the list
-    case $Picked in
+    # Carry out any specific tests and add the item to the list
+  case $Picked in
     "Cinnamon") DesktopEnvironment="Cinnamon"
         ChooseDM
       ;;
     "Deepin") DesktopEnvironment="Deepin"
         dialog --backtitle "$Backtitle" --title " Deepin desktop environment " \
-    --yesno "The deepin-extras pack includes the Deepin game center, media players, terminal & screenshot tools. Include the extras pack?\n" 10 40
+    --yesno "${_Deepin_Extras}\n" 10 40
         case $? in
           0) DDEextras="deepin-extra"
            ;;
@@ -191,7 +212,7 @@ ShoppingList() {
       ;;
     "Enlightenment") DesktopEnvironment="Enlightenment"
         dialog --backtitle "$Backtitle" --title " Enlightenment " \
-    --yesno "It is suggested that the Connman network utility and Terminology terminal emulator are installed for usability. Include them?" 10 40
+    --yesno "${_Enlightenment_Extras}" 10 40
         case $? in
           0) EnExtras="connman terminology"
            ;;
@@ -202,26 +223,6 @@ ShoppingList() {
     "Feliz") DesktopEnvironment="Xfce"
           FelizXfce="Yes"
         GoodiesXfce="xfce4-goodies"
-        # Check that yaourt and conky are not already on the list
-        AddYaourt="Yes"
-        AddConky="Yes"
-        for lux in $LuxuriesList
-        do
-          if [ ${lux} = "yaourt" ]; then
-            AddYaourt="No"
-            continue
-          elif [ ${lux} = "conky" ]; then  
-            AddConky="No"
-            continue
-          fi
-        done
-        # If not, add them
-        if [ $AddYaourt = "Yes" ]; then
-          LuxuriesList="${LuxuriesList} yaourt"
-        fi
-        if [ $AddConky = "Yes" ]; then
-          LuxuriesList="${LuxuriesList} conky"
-        fi
         ChooseDM
       ;;
     "Fluxbox") DesktopEnvironment="Fluxbox"
@@ -250,25 +251,25 @@ ShoppingList() {
       ;;
     "Xfce") DesktopEnvironment="Xfce"
         dialog --backtitle "$Backtitle" --title " Xfce desktop environment " \
-    --yesno "\nThe xfce4-goodies pack includes includes the Whisker menu, extra plugins and a number of utilities such as the mousepad editor\nInclude the $Extras pack?\n" 10 40
-      case $? in
-        0) GoodiesXfce="xfce4-goodies"
-        ;;
-        *) GoodiesXfce=""
-      esac
-      ChooseDM
-     ;;
-    *) echo "Error at $LINENO" >> feliz.log	
+    --yesno "\n${_Xfce4_Goodies0}\n${_Xfce4_Goodies1}\n${_Xfce4_Goodies2}\n" 10 40
+        case $? in
+          0) GoodiesXfce="xfce4-goodies"
+           ;;
+          *) GoodiesXfce=""
+        esac
+        ChooseDM
+      ;;
+     *) echo "Error at $LINENO" >> feliz.log
     esac
-  LuxuriesList="${LuxuriesList} ${Picked}"
+    LuxuriesList="${LuxuriesList} ${Picked}"
 done
 }
 
 ChooseDM() { # Choose a display manager unless already fixed by certain DEs
   if [ -z $DisplayManager ]; then
     Greeter=""
-    local Message="\nYou can choose one of the following display managers. Not all display managers work well with all desktop environments. If in doubt, choose LightDM. If you do not install a display manager, you will have to launch your desktop environment manually."
-    listgen1 "GDM LightDM LXDM sddm SLIM XDM" " Display Manager/Greeter " "Done"
+    local Message="\n${_ChooseDM_Message1}\n ${_ChooseDM_Message2}\n ${_ChooseDM_Message3}\n ${_ChooseDM_Message4}\n ${_ChooseDM_Message5}"
+    listgen1 "GDM LightDM LXDM sddm SLIM XDM" "${_ChooseDM_Greeter}" "${_Done}"
     Response=$(cat output.file)
     if [ $? -eq 0 ]; then
       Reply=$Response
@@ -276,7 +277,7 @@ ChooseDM() { # Choose a display manager unless already fixed by certain DEs
         "GDM") DisplayManager="gdm        "
          ;;
         "LightDM") DisplayManager="lightdm"
-            Greeter="lightdm-gtk-greeter"	
+            Greeter="lightdm-gtk-greeter"
          ;;
         "LXDM") DisplayManager="lxdm"
          ;;
@@ -296,14 +297,14 @@ FinalCheck() {
 Repeat=1
 while [ $Repeat -gt 0 ]
 do
-  local Message="These are the settings you have entered. Please check them ...\nPress <Continue> to install with these settings, or choose an item if you wish to change it: "
+  local Message="${_FinalCheck_Message1} ...\n ${_FinalCheck_Message2}"
   declare -a Settings
   Options="Root Swap Additional Kernel Grub Keyboard Locale Timezone Virtualbox Display_Manager Identity Extras"
   Settings[1]="$RootPartition $RootType                                         "
   if [ $SwapPartition ] || [ $SwapFile ]; then
     Settings[2]="$SwapPartition $SwapFile"
   else
-    Settings[2]="No provision has been made for swap"
+    Settings[2]="${_No_Swap}"
   fi
   if [ ${#AddPartList[@]} ]; then
     Counter=0
@@ -318,64 +319,73 @@ do
       Counter=$((Counter+1))
     done
   else
-    Settings[3]="No additional partitions have been allocated"
+    Settings[3]="${_No_Partitions}"
   fi
   case $Kernel in
-    1) Settings[4]="The LTS kernel will be installed"
+    1) Settings[4]="${_LTS_Kernel}"
     ;;
-    *) Settings[4]="The latest kernel will be installed"
+    *) Settings[4]="${_Latest_Kernel}"
   esac
   if [ $GrubDevice ]; then
-    Settings[5]="Grub will be installed to $GrubDevice"
+    Settings[5]="${_Grub_Install} $GrubDevice"
   else
-    Settings[5]="No provision has been made for Grub"
+    Settings[5]="${_No_Grub}"
   fi
-  Settings[6]="Keyboard is $Countrykbd"
-  Settings[7]="Locale will be set to $CountryLocale"
-  Settings[8]="Zone/subZone will be $ZONE/$SUBZONE"
+  Settings[6]="${_Keyboard_is} $Countrykbd"
+  Settings[7]="${_Locale_is} $CountryLocale"
+  Settings[8]="${_Zones} $ZONE/$SUBZONE"
   case ${IsInVbox} in
-    "VirtualBox") Settings[9]="Virtualbox guest utilities will be installed"
+    "VirtualBox") Settings[9]="${_Virtualbox_On}"
     ;;
-    *) Settings[9]="Virtualbox guest utilities will not be installed"
+    *) Settings[9]="${_Virtualbox_Off}"
   esac
   if [ -z $DisplayManager ]; then
-    Settings[10]="No Display Manager selected"
+    Settings[10]="${_No_Display_Manager}"
   else
     Settings[10]="$DisplayManager"
   fi
-  Settings[11]="Hostname = '$HostName' :  User = '$UserName'"
+  Settings[11]="${_Hostname} = '$HostName' :  ${_User} = '$UserName'"
   Settings[12]="${LuxuriesList}"
   listgen2 "$Options" " Final Check " "Continue" "Settings"
+  RetVal=$?
   Response=$(cat output.file)
-  if [ $? -eq 0 ]; then
-  case $Response in
-    "Root") ChangeRootPartition
+  Count=1
+  for i in ${Options[@]} # Convert selection into item number in list
+  do
+    if [ $i = $Response ]; then
+      break
+    fi
+    Count=$((Count+1))
+  done
+  if [ $RetVal -eq 0 ]; then
+  case $Count in
+    1) ChangeRootPartition
         AllocateRoot
     ;;
-    "Swap") ChangeSwapPartition
+    2) ChangeSwapPartition
         AllocateSwap
     ;;
-    "Additional") ChangePartitions
+    3) ChangePartitions
         MorePartitions
     ;;
-    "Kernel") SetKernel
+    4) SetKernel
     ;;
-    "Grub") SetGrubDevice
+    5) SetGrubDevice
     ;;
-    "Keyboard") getkeymap
+    6) getkeymap
     ;;
-    "Locale") setlocale
+    7) setlocale
     ;;
-    "Timezone") SetTimeZone
+    8) SetTimeZone
     ;;
-    "Virtualbox") ConfirmVbox
+    9) ConfirmVbox
     ;;
-    "Display_Manager") DisplayManager=""
+    10) DisplayManager=""
       ChooseDM
     ;;
-    "Identity") ManualSettings
+    11) ManualSettings
     ;;
-    "Extras") PickLuxuries
+    12) PickLuxuries
     ;;
     *) Repeat=0
   esac
@@ -388,22 +398,34 @@ ManualSettings() {
   declare local Settings
   while [ $Retry = "Y" ]
   do
-    local Message=" Select data to change\n <Cancel> to finish:"
-    Settings[1]="(currently $HostName)"
-    Settings[2]="(currently $UserName)"
-    listgen2 "Hostname Username" " Data Review " "" "Settings"
+    local Message=" ${_ManualSettings_Message1}\n ${_ManualSettings_Message1}:"
+    Settings[1]="(${_currently} $HostName)"
+    Settings[2]="(${_currently} $UserName)"
+
+    Options="${_Hostname} ${_Username}"
+
+    listgen2 "$Options" " Data Review " "" "Settings"
+    RetVal=$?
     Response=$(cat output.file)
-    if [ $? -eq 0 ]; then
+    Count=1
+    for i in ${Options[@]} # Convert selection into item number in list
+    do
+      if [ $i = $Response ]; then
+        break
+      fi
+      Count=$((Count+1))
+    done
+    if [ $RetVal -eq 0 ]; then
       case $Response in
-        "Hostname") dialog --backtitle "$Backtitle" --title " Data Review " --nocancel \
-         --inputbox "\nEnter new Hostname (currently $HostName)\n" 18 50 2> output.file
+        1) dialog --backtitle "$Backtitle" --title " Data Review " --nocancel \
+         --inputbox "\n${_Enter_new} ${_Hostname} (${_currently} $HostName)\n" 18 50 2> output.file
          Response=$(cat output.file)
          if [ $Response ]; then
           HostName=$Response
          fi
         ;;
-        "Username") dialog --backtitle "$Backtitle" --title " Data Review " --nocancel \
-      --inputbox "\nEnter new name for user (currently $UserName)\n" 18 50 2> output.file
+        2) dialog --backtitle "$Backtitle" --title " Data Review " --nocancel \
+      --inputbox "\n${_Enter_new} ${_Name_for_user} (${_currently} $UserName)\n" 18 50 2> output.file
          Response=$(cat output.file)
         if [ $Response ]; then
           UserName=${Response}
diff --git a/squiff/partitioning b/squiff/partitioning
--- a/squiff/partitioning
+++ b/squiff/partitioning
@@ -22,22 +22,22 @@
 
 CheckParts() { # First check of available partitions on the system
   # Test for existing partitions
-	ShowPartitions=`lsblk -l | grep 'part' | awk '{print $1}'`
+  ShowPartitions=`lsblk -l | grep 'part' | awk '{print $1}'`
   local Partitions=0
   for i in $ShowPartitions
   do
     (( Partitions+=1 ))
     break
   done
-	# If no partitions exist, offer cfdisk to create (or exit)
+  # If no partitions exist, offer cfdisk to create (or exit)
   if [ $Partitions -eq 0 ]
   then
     while [ $Partitions -eq 0 ]
     do
-      local Message="There are no partitions on the device, and at least one partition is needed for the root directory. If you choose <Do nothing> the script will terminate to allow you to partition in some other way."
+      local Message="${_No_Parts_Text1} ${_No_Parts_Text2} ${_Do_Nothing} ${_No_Parts_Text7}"
       Partitioning # Partitioning options
       if [ $Proceed -eq 3 ]; then
-        PrintOne "Exiting feliz! Hurry back, y'hear?"
+        PrintOne "${_Exiting}"
         exit
       fi
       # Check that partitions have been created
@@ -50,10 +50,10 @@ CheckParts() { # First check of available partitions on the system
       done
     done
     # Call function to generate an array of partitions
-		BuildPartitionLists # This is a first call
+    BuildPartitionLists # This is a first call
   else
     # Generate an array of partitions
-		BuildPartitionLists # This is a first call
+    BuildPartitionLists # This is a first call
     Partitions=0
     # Copy array to variable for display
     ExistingPartitions=""
@@ -62,11 +62,11 @@ CheckParts() { # First check of available partitions on the system
       ExistingPartitions="$ExistingPartitions ${PartitionArray[$Partitions]}\n"
       (( Partitions+=1 ))
     done
-    local Message="Here is a list of available partitions on all connected devices ...\n$ExistingPartitions\nIf you choose <Do nothing> the script will enable you to allocate the existing partitions."
+    local Message="${_CheckParts_Available} ...\n $ExistingPartitions\n${_Do_Nothing} ${_CheckParts_Options4}"
     Partitioning # Partitioning options
     # Call function to regenerate the array of partitions
     MakePartitionList
-	fi
+  fi
 }
 
 Partitioning() {
@@ -76,17 +76,17 @@ Partitioning() {
   do
     dialog --backtitle "$Backtitle" --title " Partitioning " --cancel-label "Do nothing"\
       --menu "$Message" 20 55 2 \
-        "Manual" "Open cfdisk so I can partition manually" \
-        "Auto" "Allow feliz to partition the whole device" 2> output.file
+        "${_Manual}" "${_Manual_Message}" \
+        "${_Auto}" "${_Auto_Message}" 2> output.file
     Proceed=$(cat output.file)
     case $Proceed in
-      "Manual") cfdisk 2>> feliz.log
+      "${_Manual}") cfdisk 2>> feliz.log
         tput setf 0 # Change foreground colour to black temporarily to hide error message
         partprobe 2>> feliz.log #Inform kernel of changes to partitions
         tput sgr0 # Reset colour
         ShowPartitions=`lsblk -l | grep 'part' | awk '{print $1}'`
       ;;
-      "Auto") AutoPartition
+      "${_Auto}") AutoPartition
       ;;
       *) Proceed=3
      esac
@@ -118,12 +118,12 @@ do
     ExistingPartitions="" # Prepare variable
     for i in $DiskDetails
     do
-      (( Counter+=1 ))    
+      (( Counter+=1 ))
       ExistingPartitions="$ExistingPartitions $i\n"
     done
     while [ -z $UseDisk ]
     do
-      local Message="There are $Counter devices available\n$ExistingPartitions\nWhich do you wish to use for installation?\n(Remember, this is auto-partition, and any data on the chosen device will be lost)"
+      local Message="${_Available_devices0} $Counter ${_Available_devices1}\n $ExistingPartitions\n${_Available_devices2}\n${_Available_devices3} ${_Available_devices4}"
       dialog --backtitle "$Backtitle" --title " auto-partition " \
       --inputbox "\n$Message\n" 18 50 2> output.file
       UseDisk=$(cat output.file)
@@ -133,10 +133,10 @@ do
         if [ $i = $UseDisk ]; then
           Counter=1
         fi
-      done 
+      done
       if [ $Counter -ne 1 ]; then
         UseDisk=""
-      fi  
+      fi
       AutoWarning
     done
   else
@@ -148,8 +148,8 @@ done
 AutoWarning() {
 while :
 do
-  dialog --backtitle "$Backtitle" --title " auto-partition " \
-    --yesno "\nThis will erase any data on '${UseDisk}'\nAre you sure you wish to continue?\n" 10 40
+  dialog --backtitle "$Backtitle" --title " auto-partition " --yes-label "${_Yes}" --no-label "${_No}"
+    --yesno "\n${_AutoWarning1} '${UseDisk}'\n${_AutoWarning2}\n" 10 40
   case $? in
     0) RunAutoPart
       if [ ${Home} = "Y" ]; then
@@ -157,16 +157,16 @@ do
         PrintHome="Home partition: ${AddPartList[0]} ${AddPartType[0]} $ShowPart3"
       fi
       dialog --backtitle "$Backtitle" --title " auto-partition " \
-    --msgbox "Partitioning of ${GrubDevice} successful\n\n$ShowPart1 ${SwapPartition}${SwapFile}\n $ShowPart2  ${RootPartition} ${RootType}\n$PrintHome\n\nYou will have the opportunity to review these later" 15 40
+    --msgbox "${_AutoWarning_Message0} ${GrubDevice} ${_successful}\n\n$ShowPart1 ${SwapPartition}${SwapFile}\n $ShowPart2  ${RootPartition} ${RootType}\n$PrintHome\n\n${_AutoWarning_Message1}" 15 40
       break
       ;;
     *) UseDisk=""
       break
   esac
-done  
+done
 }
 
-FileSystem() { 
+FileSystem() {
   case $1 in
   "nocancel") local Cancel="--$1"
   ;;
@@ -210,19 +210,19 @@ EditLabel() { # Called by AllocateRoot, AllocateSwap and MorePartitions
 # Allows user to keep, edit or remove an existing label
 Label="${Labelled[$1]}"
 if [ -n ${Label} ]; then
-  dialog --backtitle "$Backtitle" --title "  Edit Partition Label  " \
-      --menu "The partition you have chosen is labelled '${Label}'" 18 50 3 \
-        "1" "Keep existing label" \
-        "2" "Delete label" \
-        "3" "Enter a new label" 2> output.file
+  dialog --backtitle "$Backtitle" --title " - ${_Label_Title} - " --no-shadow \
+      --menu "${_EditLabel0} '${Label}'" 18 50 3 \
+        "1" "${_existing_label}" \
+        "2" "${_delete_label}" \
+        "3" "${_new_label}" 2> output.file
   Response=$(cat output.file)
   case $Response in
     1) LabellingArray[$PartitionID]=$Label # Keep saved label
     ;;
     2) LabellingArray[$PartitionID]="" # Empty label
     ;;
-    *) dialog --backtitle "$Backtitle" --title " Edit Partition Label " \
-      --inputbox "Enter the new name for $PartitionID" 10 50 2> output.file
+    *) dialog --backtitle "$Backtitle" --title " - ${_Label_Title} - " --no-shadow \
+      --inputbox "$PartitionID \n${_new_label} ..." 10 50 2> output.file
       Response=$(cat output.file)
       LabellingArray[$PartitionID]=$Response # Save new label
   esac
@@ -231,13 +231,13 @@ fi
 
 BuildPartitionLists() { # First called by CheckParts to generate details of partitions
   # for display, then by feliz to prepare partition arrays for selection for root, swap and others
-  # 1) First get a list of all partitions up to sda99 | select first field | remove /dev/ | remove colon 
+  # 1) First get a list of all partitions up to sda99 | select first field | remove /dev/ | remove colon
   ListTypeIDs=`sudo blkid /dev/sd* | grep ' TYPE' | awk '{print $1}' | cut -c 6- | sed s/://g`
-  # Then get matching list of types, removing unwanted text (TYPE=) and quotes 
-  ListTypes=`sudo blkid /dev/sd* | grep ' TYPE' | awk '{print $(NF-1)}' | cut -c 6- | sed s/\"//g` 
+  # Then get matching list of types, removing unwanted text (TYPE=) and quotes
+  ListTypes=`sudo blkid /dev/sd* | grep ' TYPE' | awk '{print $(NF-1)}' | cut -c 6- | sed s/\"//g`
   # Add records from those two indexed arrays into the associative array
   local Counter=0
-  for i in ${ListTypeIDs} 
+  for i in ${ListTypeIDs}
   do
     x=0
     for l in ${ListTypes}
@@ -283,7 +283,7 @@ BuildPartitionLists() { # First called by CheckParts to generate details of part
   done
   local HowManyFlagged="${#Flagged[@]}"
   # 4) Prepare list of short identifiers (sda1 sda2 ...)
-  PartitionList="" 
+  PartitionList=""
   ShowPartitions=`lsblk -l | grep 'part' | awk '{print $1}'`
   # 5) Run through short identifiers, checking the three arrays for a match
   Counter=0 # For count of partitions
@@ -295,7 +295,7 @@ BuildPartitionLists() { # First called by CheckParts to generate details of part
     until [ ${x} -eq ${HowManyFlagged} ]
     do
       if [ $part = "${Flagged[$x]}" ]; then
-        Bootable="(Bootable)"
+        Bootable="(${_Bootable})"
         break
       else
         Bootable=""
@@ -321,7 +321,7 @@ BuildPartitionLists() { # First called by CheckParts to generate details of part
 
 UpdateArray() { # Remove the selected partition from $PartitionArray[]
   # Called by AllocateRoot, AllocateSwap and MorePartitions
-	local Counter=0
+  local Counter=0
   declare -a NewArray  # Empty NewArray
   # Build NewArray excluding the partition selected in the calling function
   for p in "${PartitionArray[@]}"
@@ -345,55 +345,55 @@ UpdateArray() { # Remove the selected partition from $PartitionArray[]
 }
 
 AllocateRoot() {
-  # Display partitions for user-selection	
-	# Uses list of all available partitions in PartitionList
-	Remaining=""
+  # Display partitions for user-selection
+  # Uses list of all available partitions in PartitionList
+  Remaining=""
   Partition=""
-	PartitionType=""
-  local Message="Select a partition to use as /root\n"
-  listgen2 "$PartitionList" " Partitions " "nocancel" "PartitionArray"
+  PartitionType=""
+  local Message="${_AllocateRoot0} /${_root}\n"
+  listgen2 "$PartitionList" "${_Partitions}" "nocancel" "PartitionArray"
   Reply=$(cat output.file)
   PassPart="$Reply"
   SetLabel "$Reply"
   UpdateArray # Remove the selected partition from $PartitionArray[]
-  local Counter=0  
+  local Counter=0
   for i in ${PartitionList}
   do
-		(( Counter+=1 ))
+    (( Counter+=1 ))
     if [ $i = $Reply ]; then
-			Partition="$i"
-			RootPartition="/dev/$i"
+      Partition="$i"
+      RootPartition="/dev/$i"
       # Before going to FileSystem, see if the partition is already formatted
       CheckPartition
       # Now select a filesystem
       if [ ${CurrentType} ]; then
-        local Message="$Message\nYou can choose to leave it as it is, by selecting '<None>', but be aware that not reformatting the root partition may have unexpected consequences."
-        FileSystem "None"
+        local Message="$Message\n${_AllocateRoot1} ${_AllocateRoot2} ${_AllocateRoot3}"
+        FileSystem "${_None}"
       else
-        local Message="Please now select the file system for ${Partition} ... It is not recommended to mix the btrfs file-system with others.\n"
-        FileSystem "None"
+        local Message="${_select_filesystem1} ${Partition} ... ${_select_filesystem2}\n"
+        FileSystem "${_None}"
       fi
-			if [ -z ${PartitionType} ] && [ ${CurrentType} ]; then
-				RootType=""
-			else
+      if [ -z ${PartitionType} ] && [ ${CurrentType} ]; then
+        RootType=""
+      else
         RootType="${PartitionType}"
         Label="${Labelled[${PassPart}]}"
         if [ -n "${Label}" ]; then
           EditLabel $PassPart
         fi
       fi
-		else
-			Remaining="$Remaining $i"	# Add next available partition
-		fi
-	done
-  PartitionList=$Remaining			# Replace original PartitionList with remaining options
+    else
+      Remaining="$Remaining $i" # Add next available partition
+    fi
+  done
+  PartitionList=$Remaining      # Replace original PartitionList with remaining options
 }
 
 CheckPartition() {
 # Finds if there is an existing file system on the selected partition
 CurrentType=`file -sL ${Partition} | grep "ext" | cut -c26-30`
 if [ ${CurrentType} ]; then
-  local Message="The selected partition ${Partition} is currently formatted to ${CurrentType}\nReformatting it will remove all data currently on it."
+  local Message="${_CheckPartition0} ${Partition} ${_CheckPartition1} ${CurrentType}\n${_CheckPartition2}"
 else
  local Message=""
 fi
@@ -416,8 +416,8 @@ then
   CopyArray[${Counter}]="Swapfile"   # Add 'Swapfile' to array of available partitions
   PickFrom="$PartitionList Swapfile" # and make copy of PartitionList with 'Swapfile' added
   Width=50                           # Set window minimum width for listgen2
-  local Message="Select a partition for swap, or allocate a swap file. Warning: Btrfs does not support swap files.\nIf you select <None> no swap will be allocated" # Passed to listgen2
-  listgen2 "$PickFrom" "Partitions" "None" "CopyArray" # listgen2 builds complex dialog menu
+  local Message="${_AllocateSwap1}\n${_AllocateSwap2}\n${_AllocateSwap3}" # Passed to listgen2
+  listgen2 "$PickFrom" "${_Partitions}" "${_None}" "CopyArray" # listgen2 builds complex dialog menu
   if [ $? -ne 0 ]; then              # If <Cancel> selected
     Result="Done"                    # Prepare reporting variable before exiting
     SwapPartition=""
@@ -432,8 +432,9 @@ then
     SwapPartition="/dev/$Result"     # All other options are a partition in form 'sd*n'
     IsSwap=`sudo blkid ${SwapPartition} | grep 'swap' | awk '{print $1}'` # Check if already a swap
     if [ -n "$IsSwap" ]; then                                     # If it is, offer yes/no ...
-      dialog --backtitle "$Backtitle" --title " Swap Partition " --yesno "$Result is already formatted as a swap partition, do you wish to reformat it?" 10 40
-      case $? in                     # ... and use $? (exit status) to set variable
+      dialog --backtitle "$Backtitle" --title " Swap Partition " --yes-label "${_Yes}" --no-label "${_No}" --yesno "$Result ${_AllocateSwap5} ${_AllocateSwap6}" 10 40
+      RetVal=$?
+      case $RetVal in                # ... and use $? (exit status) to set variable
       0) MakeSwap="Y"                # used during installation
       ;;
       *) MakeSwap="N"
@@ -450,7 +451,7 @@ then
     for p in "${PartitionArray[@]}"  # Then go through the array ...
     do
       First=`echo $p | awk '{print $1}'` # Separate first field, and use it
-      Remaining="$Remaining $First"	     # in building the new list
+      Remaining="$Remaining $First"      # in building the new list
     done
   fi
 fi
@@ -459,27 +460,27 @@ PartitionList=$Remaining             # Replace original PartitionList with remai
 
 SetSwapFile() {
 LoopRepeat="Y"
-local Message="Allocate the size of your swap file (M = Megabytes, G = Gigabytes) [eg: 512M or 2G]"
+local Message="${_SetSwapFile1} [eg: 512M or 2G]"
 while [ ${LoopRepeat} = "Y" ]
 do
-  dialog --backtitle "$Backtitle" --title " auto-partition " \
+  dialog --backtitle "$Backtitle" --title " auto-partition " --no-shadow
       --inputbox "\n$Message\n" 18 50 2> output.file
   Response=$(cat output.file)
   RESPONSE="${Response^^}"
-	# Check that entry includes 'M or G'
-	CheckInput=(`echo $RESPONSE | grep "G\|M"`)
+  # Check that entry includes 'M or G'
+  CheckInput=(`echo $RESPONSE | grep "G\|M"`)
   echo
-	if [ -z ${CheckInput} ]; then
-    local Message="You must include M or G\n$Message"
-		SwapFile=""
-	else
+  if [ -z ${CheckInput} ]; then
+    local Message="${_SetSwapFile3}\n$Message"
+    SwapFile=""
+  else
     SwapFile=$RESPONSE
     LoopRepeat="N"
   fi
   if [ ${LoopRepeat} = "N" ]; then
     break
-  fi 
-done 
+  fi
+done
 }
 
 MorePartitions() { # For any unallocated partitions. Uses PartitionList and PartitionArray
@@ -490,11 +491,11 @@ MorePartitions() { # For any unallocated partitions. Uses PartitionList and Part
   do
     (( Elements+=1 ))
   done
-  while [ $Elements -gt 0 ]  
+  while [ $Elements -gt 0 ]
   do
     Remaining=""
-    local Message="The following partitions remain unallocated.\nIf you wish to use one, select it from the list, or choose <Done> to finish partitioning."
-    listgen2 "$PartitionList" "Partitions" "Done" "PartitionArray"
+    local Message="${_MorePartitions1}\n${_MorePartitions2} ${_MorePartitions3}"
+    listgen2 "$PartitionList" "${_Partitions}" "${_Done}" "PartitionArray"
     Response=$?
     if [ $Response -gt 0 ]; then # ie: <Done>
       Elements=0
@@ -521,7 +522,7 @@ MorePartitions() { # For any unallocated partitions. Uses PartitionList and Part
         (( AddedToRemaining+=1 )) # And increment the count
       fi
     done
-    PartitionList=$Remaining	# Replace original PartitionList with temp list
+    PartitionList=$Remaining  # Replace original PartitionList with temp list
     Elements=$AddedToRemaining
   done
   # Ensure that if AddPartList (the defining array) is empty, all others are too
@@ -536,56 +537,55 @@ MorePartitions() { # For any unallocated partitions. Uses PartitionList and Part
 MakePartition() { # Called by MorePartitions
   # Add the selected partition to the array for extra partitions
   # 1) Save to AddPartList (eg: /dev/sda5)
-	ExtraPartitions=${#AddPartList[@]}
-	AddPartList[$ExtraPartitions]="${Partition}"
+  ExtraPartitions=${#AddPartList[@]}
+  AddPartList[$ExtraPartitions]="${Partition}"
   CheckPartition   # Before going to FileSystem, check the partition
   if [ ${CurrentType} ]; then
-    local Message="You can choose to leave it as it is, by selecting 'Done', but not reformatting an existing partition can have unexpected consequences."
+    local Message="${_MakePartition1} ${_MakePartition2}"
   fi
   # 2) Select filesystem
-  FileSystem "None"
-	AddPartType[$ExtraPartitions]="${PartitionType}" 	# Add it to AddPartType list  
+  FileSystem "${_None}"
+  AddPartType[$ExtraPartitions]="${PartitionType}"  # Add it to AddPartType list
   # 3) Get a mountpoint
-	LoopRepeat="Y"
-  local Message="Enter a mountpoint for ${Partition} (eg: '/home')"
-	while [ ${LoopRepeat} = "Y" ]
-	do
-    dialog --backtitle "$Backtitle" --title " auto-partition " \
-      --inputbox "\n$Message\n" 18 50 2> output.file
+  LoopRepeat="Y"
+  local Message="${_MakePartition3} ${Partition} ${_MakePartition4}"
+  while [ ${LoopRepeat} = "Y" ]
+  do
+    dialog --backtitle "$Backtitle" --title " - ${_Partitions} - " --no-shadow --inputbox "\n$Message\n" 18 50 2> output.file
     Response=$(cat output.file)
- 		# Check that entry includes '/'
-		CheckInput=(`echo $Response | cut -c1`)
-		case ${CheckInput} in
-      "") PrintOne "You must enter a valid name"
-					PartMount=""
+    # Check that entry includes '/'
+    CheckInput=(`echo $Response | cut -c1`)
+    case ${CheckInput} in
+      "") PrintOne "${_MakePartition5}"
+          PartMount=""
           ;;
-			*) if [ ${CheckInput} != "/" ]; then
-						PartMount="/${Response}"
-				else
-						PartMount="${Response}"
-				fi
+      *) if [ ${CheckInput} != "/" ]; then
+            PartMount="/${Response}"
+        else
+            PartMount="${Response}"
+        fi
     esac
     # Check that the mountpoint has not already been used
-		MountPointCounter=0
-		if [ -z ${AddPartMount} ]; then
-			LoopRepeat="N"
-		else
+    MountPointCounter=0
+    if [ -z ${AddPartMount} ]; then
+      LoopRepeat="N"
+    else
       # Go through AddPartMount checking each item against PartMount
-			for MountPoint in ${AddPartMount}
-			do 
-				MountPointCounter=$((MountPointCounter+1))
-				if [ $MountPoint = $PartMount ]; then
-					local Message="Mountpoint ${PartMount} has already been used. Please use a different mountpoint.\n$Message"
-				else
-					LoopRepeat="N"
-					break
-				fi
-			done 
-		fi 
-		if [ ${LoopRepeat} = "N" ]  
-		then
-			break
-		fi 
-	done 
-	AddPartMount[$ExtraPartitions]="${PartMount}"
+      for MountPoint in ${AddPartMount}
+      do
+        MountPointCounter=$((MountPointCounter+1))
+        if [ $MountPoint = $PartMount ]; then
+          local Message="${_Mountpoint} ${PartMount} ${_MakePartition6}\n$Message"
+        else
+          LoopRepeat="N"
+          break
+        fi
+      done
+    fi
+    if [ ${LoopRepeat} = "N" ]
+    then
+      break
+    fi
+  done
+  AddPartMount[$ExtraPartitions]="${PartMount}"
 }
diff --git a/squiff/various b/squiff/various
--- a/squiff/various
+++ b/squiff/various
@@ -10,15 +10,39 @@
 # -------------------------      -------------------------
 # Functions           Line       Functions           Line
 # -------------------------      -------------------------
-# PrintOne              22       SetGrubDevice        128
-# DisplayProgress       25       arch_chroot          126
-# ProgressArray         47       MountPartitions      130
-# SetKernel             61       InstallKernel        190
-# ConfirmVbox           73       SetRootPassword      244
-# MakePartitionList    104       SetUserPassword      261
-      
+# SetLanguage           21
+# PrintOne              44       SetGrubDevice        150
+# DisplayProgress       47       arch_chroot          155
+# ProgressArray         64       MountPartitions      160
+# SetKernel             83       InstallKernel        222
+# ConfirmVbox           95       SetRootPassword      266
+# MakePartitionList    126       SetUserPassword      285
+
+SetLanguage() { # User selects language, which is then fixed
+  dialog --clear --backtitle "$_Backtitle" --title " - Language - " --menu "Choose your language" 15 40 7 \
+        "English" "English" \
+        "French" "Francais" \
+        "Polish" "Polski" \
+        "Portuguese" "Português" \
+        "Romanian" "Română" \
+        "Spanish" "Espanhol" \
+        "Serbian" "Srpski" 2> feliz.output
+    RetVal=$?
+    case $RetVal in
+      0) # ie: Language selected
+        Language=`cat feliz.output`
+        Language="${Language,,}" # Make lower case
+        LanguageFile="feliz.${Language}"
+        cp $LanguageFile feliz.language # Set for future use
+      ;;
+      *) # Catchall for <Cancel> button (1) selected (no action) or Esc
+        cp feliz.english feliz.language # Set default language to English
+    esac
+  source feliz.language
+}
+
 PrintOne() {  # Arguments: "Component" "Patient"
-  dialog --backtitle "$Backtitle" --title " Information " --no-shadow --infobox "$1\n$2\n" 5 55 ; sleep 1 &
+  dialog --backtitle "$Backtitle" --title " - ${_Information} - " --no-shadow --infobox "$1\n$2\n" 5 55 ; sleep 1 &
 }
 
 TPecho() { # For compatibility with Cliff
@@ -28,20 +52,20 @@ TPecho() { # For compatibility with Cliff
 DisplayProgress() { # Revised code for displaying progress for longer processes
   Estimate=$2 # Numeric value passed as multiple of 10
   local Message="$1" # Text passed to appear above progress bar
-  local Sleep=$(( $Estimate / 10 )) # Set sleep period to one tenth of total time 
+  local Sleep=$(( $Estimate / 10 )) # Set sleep period to one tenth of total time
   local Percent=0
   (
   until [ $Percent -gt 100 ]
   do
     echo "XXX"
     echo $Percent
-    echo "\n  $Message\n  Processing may continue after gauge shows 100%\n  Please be patient ..."
+    echo "\n  $Message\n  ${_Gauge}\n  ${_Patient} ..."
     echo "XXX"
     Percent=`expr $Percent + 10`
     sleep $Sleep
   done
   ) |
-  dialog --backtitle "$Backtitle" --title " Progress " --no-shadow --gauge "" 9 60 0 &
+  dialog --backtitle "$Backtitle" --title " - ${_Progress} - " --no-shadow --gauge "" 9 60 0 &
 }
 
 ProgressArray() {
@@ -49,20 +73,20 @@ ProgressArray() {
   local Title=" $1 "
   # Receives PassArray comprising all the programs
   # 1) Count items in the array
-  n=${#PassArray[*]}; 
+  n=${#PassArray[*]};
   # 2) Redirect dialog commands input using substitution
   dialog --title "$Title" --no-shadow --gauge "" 8 60 < <(
   # 3) set counter - it will increase on each parse
    i=0
-  # 4) read each item from the array 
+  # 4) read each item from the array
   for f in "${PassArray[@]}"
   do
     # ... calculate progress
     PCT=$(( 100*(++i)/n ))
-    # ... update dialog box 
+    # ... update dialog box
     echo "XXX"
     echo "$PCT"
-    echo "\n  Installing $f"
+    echo "\n  ${_Installing} $f"
     echo "XXX"
     # ... install $f
     pacstrap /mnt $f &>> feliz.log
@@ -71,14 +95,14 @@ ProgressArray() {
 }
 
 SetKernel() {
-  local Message="The Long-Term-Support kernel (LTS) offers stabilty,while the Latest kernel has all the new features. If in doubt, choose LTS."
-  listgen1 "LTS Latest" " Choose your kernel " "nocancel"
+  local Message="${_SetKernel1} ${_SetKernel2} ${_SetKernel3}"
+  listgen1 "${_LTS} ${_Latest}" " - ${_Choose_kernel} - " "nocancel"
   case $(cat output.file) in
-    "LTS") Kernel=1 # Set the Kernel variable (1 = LTS; 2 = Latest)
+    "${_LTS_kernel}") Kernel=1 # Set the Kernel variable (1 = LTS; 2 = Latest)
     ;;
-    "Latest") Kernel=2 # Set the Kernel variable (1 = LTS; 2 = Latest)
+    "${_Latest_kernel}") Kernel=2 # Set the Kernel variable (1 = LTS; 2 = Latest)
     ;;
-    *) echo "Illogical, cap'n" >> feliz.log
+    *) echo "${_Failure}" >> feliz.log
   esac
 }
 
@@ -86,11 +110,10 @@ ConfirmVbox() {
   Retry="Y"
   until [ $Retry = "N" ]
   do
-    local Message="It appears that feliz is running in Virtualbox.\nIf it is, feliz can install Virtualbox guest utilities and make appropriate settings for you.\n\nInstall Virtualbox guest utilities? (y/n): "
-    dialog --backtitle "$Backtitle" --title " auto-partition " \
-    --yesno "\n$Message\n" 10 40
-    # Use $? (exit status) ...
-    case $? in
+    local Message="${_ConfirmVbox1}\n${_ConfirmVbox2} ${_ConfirmVbox3}\n\n${_ConfirmVbox4}"
+    dialog --backtitle "$Backtitle" --title " auto-partition " --yes-label "${_Yes}" --no-label "${_No}" --no-shadow --yesno "\n$Message\n" 10 40
+    RetVal=$?
+    case $RetVal in
       0) IsInVbox="VirtualBox"
         Retry="N"
       ;;
@@ -103,7 +126,7 @@ ConfirmVbox() {
 MakePartitionList() {
 # Call BuildPartitionLists function to generate an array of partitions
 # This is not a first call, so first empty the existing array
- 	local x=0
+  local x=0
   local HowMany="${#PartitionArray[@]}"
   until [ ${x} -eq ${HowMany} ]
   do
@@ -117,8 +140,8 @@ SetGrubDevice() {
   DEVICE=""
   DevicesList="$(lsblk -d | awk '{print "/dev/" $1}' | grep 'sd\|hd\|vd')";
   GrubDevice=""
-	local Message="Select the device where Grub is to be installed.\nNote that if you select the <Cancel> option, Grub will not be installed, and you will have to make alternative arrangements for booting your new system."
-	listgen1 "${DevicesList}" "Devices" ""
+  local Message="${_SetGrubDevice1}\n${_SetGrubDevice2} ${_SetGrubDevice3} ${_SetGrubDevice4}"
+  listgen1 "${DevicesList}" "${_Devices}" ""
   if [ $? -gt 0 ]; then # <Cancel> selected
    GrubDevice=""
   else
@@ -128,13 +151,13 @@ SetGrubDevice() {
 
 arch_chroot() {  # From Lution AIS
   arch-chroot /mnt /bin/bash -c "${1}" &>> feliz.log
-}  
+}
 
 MountPartitions() {
   case $RootType in
-  "") echo "Not formatting root partition" &>> feliz.log
+  "") echo "Not formatting root partition" >> feliz.log
   ;;
-  *) PrintOne "Preparing and mounting partitions" ""
+  *) PrintOne "${_Preparing_and_mounting}" ""
     umount ${RootPartition} /mnt >/dev/null &>> feliz.log
     # Check if replacing existing ext3/4 partition with btrfs
     CurrentType=`file -sL ${RootPartition} | grep 'ext\|btrfs' | cut -c26-30` &>> feliz.log
@@ -168,7 +191,7 @@ MountPartitions() {
   for id in ${AddPartList}
   do
     umount ${id} /mnt${AddPartMount[$Counter]} >/dev/null &>> feliz.log
-    mkdir -p /mnt${AddPartMount[$Counter]} &>> feliz.log	# eg: mkdir -p /mnt/home
+    mkdir -p /mnt${AddPartMount[$Counter]} &>> feliz.log  # eg: mkdir -p /mnt/home
     # Check if replacing existing ext3/4 partition with btrfs
     CurrentType=`file -sL ${AddPartType[$Counter]} | grep 'ext\|btrfs' | cut -c26-30`
     if [ ${AddPartType[$Counter]} = "btrfs" ] && [ ${CurrentType} != "btrfs" ]; then
@@ -183,57 +206,57 @@ MountPartitions() {
       fi
       mke2fs ${Label} -t ${AddPartType[$Counter]} ${id} &>> feliz.log # eg: mke2fs -L Arch-Home -t ext4 /dev/sda3
     fi
-    mount ${id} /mnt${AddPartMount[$Counter]} &>> feliz.log	# eg: mount /dev/sda3 /mnt/home
-		Counter=$((Counter+1))
-	done
+    mount ${id} /mnt${AddPartMount[$Counter]} &>> feliz.log # eg: mount /dev/sda3 /mnt/home
+    Counter=$((Counter+1))
+  done
 }
 
 InstallKernel() { # Kernel and some other core systems
-  DisplayProgress "Installing shell" 40
-  pacstrap /mnt base-devel bash &>> feliz.log 
+  DisplayProgress "${_Installing} bash" 40
+  pacstrap /mnt base-devel bash &>> feliz.log
   # Create array of all the programs to pass to installing function
   PassArray=() # Ensure array is empty
   PassArray=( btrfs-progs bzip2 coreutils cryptsetup device-mapper dhcpcd diffutils e2fsprogs file filesystem findutils glibc inetutils iproute2 iputils jfsutils less licenses logrotate lvm2 man-db man-pages mdadm netctl ntp pciutils pcmciautils procps-ng psmisc s-nail shadow sudo sysfsutils systemd-sysvcompat tar texinfo usbutils util-linux wget which xfsprogs gawk gcc-libs gettext gksu grep zip nano openssh pacman perl reiserfsprogs screenfetch sed unrar unzip vi vim xarchiver xorg-xedit xterm )
-  ProgressArray " Installing cli tools and extras " # Install each one using pacstrap
+  ProgressArray " ${_Installing} ${_cli_tools} " # Install each one using pacstrap
   # Enable sshd
   arch_chroot "systemctl enable sshd.service" >/dev/null
-  
+
   case $Kernel in
-  1) DisplayProgress "Installing LTS kernel" 50
+  1) DisplayProgress "${_Installing} ${_LTS} ${_kernel}" 50
     pacstrap /mnt linux-lts &>> feliz.log
     if [ -n ${IsInVbox} ] && [ $Scope != "Basic" ]; then # Installing in Virtualbox
       pacstrap /mnt virtualbox-guest-utils virtualbox-guest-modules-lts  virtualbox-guest-dkms &>> feliz.log
       echo blacklist i2c_piix4 > /mnt/etc/modprobe.d/modprobe.conf &>> feliz.log  # To overcome piix4 Virtualbox error
       cp virtualbox.conf /mnt/etc/modules-load.d/ &>> feliz.log
     fi
-  ;;  
-  *) DisplayProgress "Installing Latest kernel" 50
+  ;;
+  *) DisplayProgress "${_Installing} ${_Latest} ${_kernel}" 50
     pacstrap /mnt linux &>> feliz.log
     if [ -n ${IsInVbox} ] && [ $Scope != "Basic" ]; then # Installing latest kernel in Virtualbox
       pacstrap /mnt virtualbox-guest-utils virtualbox-guest-dkms &>> feliz.log
       echo blacklist i2c_piix4 > /mnt/etc/modprobe.d/modprobe.conf &>> feliz.log  # To overcome piix4 Virtualbox error
       cp virtualbox.conf /mnt/etc/modules-load.d/ &>> feliz.log
     fi
-  esac                                                   
-  
+  esac
+
  # PrintOne "Installing opensource video drivers" ""
   pacstrap /mnt xf86-video-vesa xf86-video-nouveau &>> feliz.log # Install opensource video drivers
 }
 
 SetRootPassword() {
-  Backtitle="Success! Finished installing in $DIFFMIN minutes and $DIFFSEC seconds"
-  Title=" Passwords "
+  Backtitle="${_Success} ${_Finished} $DIFFMIN ${_minutes} $DIFFSEC ${_seconds}"
+  Title="${_Passwords}"
   Repeat="Y"
   while [ $Repeat = "Y" ]
   do
-    dialog --backtitle "$Backtitle" --title "$Title" --nocancel \
-     --insecure --passwordbox "Enter a password for root" 8 40 2> output.file
+    dialog --backtitle "$Backtitle" --title " - $Title - " --nocancel \
+     --insecure --passwordbox "${_enter_password} ${_root}" 8 40 2> output.file
     Pass1=`cat output.file`
     dialog --backtitle "$Backtitle" --title "$Title" --nocancel \
-      --insecure --passwordbox "Re-enter root password" 8 40 2> output.file
+      --insecure --passwordbox "${_enter_again} ${_root}" 8 40 2> output.file
     Pass2=`cat output.file`
     if [ -z ${Pass1} ] || [ -z ${Pass2} ]; then
-      PrintOne "Passwords cannot be blank. Try again ..."
+      PrintOne "${_no_blank} ${_Try_again} ..."
       continue
     fi
     if [ $Pass1 = $Pass2 ]; then
@@ -242,7 +265,7 @@ SetRootPassword() {
      rm /tmp/.passwd &>> feliz.log
      Repeat="N"
     else
-      PrintOne "Passwords don't match. Try again"
+      PrintOne "${_no_match} ${_Try_again}"
     fi
   done
 }
@@ -251,14 +274,14 @@ SetUserPassword() {
   Repeat="Y"
   while [ $Repeat = "Y" ]
   do
-    dialog --backtitle "$Backtitle" --title "$Title" --nocancel\
-      --insecure --passwordbox "Enter a password for $UserName" 8 40 2> output.file
+    dialog --backtitle "$Backtitle" --title " - $Title - " --nocancel\
+      --insecure --passwordbox "${_enter_password} $UserName" 8 40 2> output.file
     Pass1=`cat output.file`
     dialog --backtitle "$Backtitle" --title "$Title" --nocancel \
-      --insecure --passwordbox "Re-enter ${UserName}'s password" 8 40 2> output.file
+      --insecure --passwordbox "${_enter_again} ${UserName}" 8 40 2> output.file
     Pass2=`cat output.file`
     if [ -z ${Pass1} ] || [ -z ${Pass2} ]; then
-      PrintOne "Passwords cannot be blank. Try again"
+      PrintOne "${_no_blank} ${_Try_again}"
       continue
     fi
     if [ $Pass1 = $Pass2 ]; then
@@ -267,7 +290,7 @@ SetUserPassword() {
       rm /tmp/.passwd &>> feliz.log
       Repeat="N"
     else
-      PrintOne "Passwords don't match. Try again"
+      PrintOne "${_no_match} ${_Try_again}"
     fi
   done
 }
